"use client";
import { useEffect,useState } from "react";
import { safeReleaseUrl, type ReleaseState } from "@/lib/desktop/release-check";
export function UpdatePanel({installedVersion}:{installedVersion:string}) {
 const [state,setState]=useState<ReleaseState|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch("/api/desktop/updates",{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Histórico indisponível.");setState(await r.json());}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[]);
 const check=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/desktop/updates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"check"})});const value=await r.json();if(!r.ok)throw Error(value.error??"Falha na consulta.");setState(value);}catch(e){setError(e instanceof Error?e.message:"Falha na consulta.");}finally{setBusy(false);}};
 const href=state?.releaseUrl?safeReleaseUrl(state.releaseUrl):null;
 return <section className="prefs-form update-panel" aria-labelledby="updates-title"><h2 id="updates-title">Versões do aplicativo</h2><p>Versão instalada: <strong>{installedVersion}</strong></p><p>Última consulta bem-sucedida: {state?.lastSuccessfulAt?new Date(state.lastSuccessfulAt).toLocaleString("pt-BR"):"nenhuma"}</p><p role="status">{state?.message??"Ainda não consultado."}{state?.cached?" Resultado em cache; aguarde o intervalo para nova consulta.":""}</p>{state?.latestVersion&&<p>Última release estável: {state.latestVersion}</p>}<button type="button" className="filter-button" disabled={busy} onClick={check}>{busy?"Consultando…":"Consultar releases públicas"}</button><p className="hint">Consulta somente o GitHub público do LawyerWeb, sem credenciais. Intervalo: 15 minutos após sucesso e 5 minutos após falha.</p>{error&&<p role="alert" className="desktop-note warn">{error}</p>}{href&&<a href={href} target="_blank" rel="noopener noreferrer">Ler a release no repositório</a>}{state?.notes&&<details><summary>Notas da release · texto</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{state.notes}</pre></details>}<p><strong>Instalação indisponível.</strong> Assinatura e fluxo seguro precisam ser aprovados. Nenhum instalador é baixado ou executado.</p></section>;
}
