import { P } from "@/lib/authz/permissions";

const all = ["*"];

export const DEFAULT_ROLES = [
  { key: "OWNER", name: "Proprietário / Sócio administrador", level: 100, allow: all },
  { key: "MANAGING_PARTNER", name: "Sócio / Coordenador", level: 90, allow: [
    P.MEMBERS_MANAGE,P.MATTERS_VIEW,P.MATTERS_EDIT,P.CLIENTS_VIEW,P.CLIENTS_EDIT,
    P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.DEADLINES_CONFIRM,P.DEADLINES_COMPLETE,P.DEADLINES_MANAGE,P.INBOX_TRIAGE,
    P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.DOCUMENTS_SIGN,
    P.CONTRACTS_VIEW,P.CONTRACTS_EDIT,P.FINANCE_VIEW,P.REPORTS_VIEW,P.AUDIT_VIEW,P.AGENT_USE,P.AGENT_MANAGE
  ]},
  { key: "SENIOR_LAWYER", name: "Advogado sênior", level: 80, allow: [
    P.MATTERS_VIEW,P.MATTERS_EDIT,P.CLIENTS_VIEW,P.CLIENTS_EDIT,
    P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.DEADLINES_CONFIRM,P.DEADLINES_COMPLETE,P.INBOX_TRIAGE,
    P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.DOCUMENTS_SIGN,
    P.CONTRACTS_VIEW,P.CONTRACTS_EDIT,P.REPORTS_VIEW,P.AGENT_USE
  ]},
  { key: "LAWYER", name: "Advogado", level: 70, allow: [
    P.MATTERS_VIEW,P.MATTERS_EDIT,P.CLIENTS_VIEW,
    P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.DEADLINES_CONFIRM,P.DEADLINES_COMPLETE,P.INBOX_TRIAGE,
    P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.DOCUMENTS_SIGN,
    P.CONTRACTS_VIEW,P.CONTRACTS_EDIT,P.AGENT_USE
  ]},
  { key: "ASSOCIATE", name: "Advogado associado", level: 65, allow: [
    P.MATTERS_VIEW,P.MATTERS_EDIT,P.CLIENTS_VIEW,
    P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.DEADLINES_COMPLETE,P.INBOX_TRIAGE,
    P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.CONTRACTS_VIEW,P.AGENT_USE
  ]},
  { key: "LEGAL_OPS", name: "Controladoria jurídica / Legal Ops", level: 75, allow: [
    P.MATTERS_VIEW,P.CLIENTS_VIEW,P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.DEADLINES_CONFIRM,
    P.DEADLINES_COMPLETE,P.DEADLINES_MANAGE,P.INBOX_TRIAGE,P.TASKS_VIEW,P.TASKS_EDIT,
    P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.REPORTS_VIEW,P.AUDIT_VIEW,P.AGENT_USE
  ]},
  { key: "PARALEGAL", name: "Paralegal / Assistente", level: 50, allow: [
    P.MATTERS_VIEW,P.CLIENTS_VIEW,P.DEADLINES_VIEW,P.DEADLINES_CREATE,P.INBOX_TRIAGE,
    P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.AGENT_USE
  ]},
  { key: "FINANCE", name: "Financeiro", level: 40, allow: [P.CLIENTS_VIEW,P.FINANCE_VIEW,P.FINANCE_EDIT,P.REPORTS_VIEW] },
  { key: "ADMIN", name: "Administrativo", level: 35, allow: [P.CLIENTS_VIEW,P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW] },
  { key: "INTERN", name: "Estagiário", level: 25, allow: [P.MATTERS_VIEW,P.CLIENTS_VIEW,P.DEADLINES_VIEW,P.TASKS_VIEW,P.TASKS_EDIT,P.DOCUMENTS_VIEW,P.DOCUMENTS_EDIT,P.AGENT_USE] },
  { key: "AUDITOR", name: "Somente leitura / Auditor", level: 10, allow: [P.MATTERS_VIEW,P.CLIENTS_VIEW,P.DEADLINES_VIEW,P.TASKS_VIEW,P.DOCUMENTS_VIEW,P.CONTRACTS_VIEW,P.FINANCE_VIEW,P.REPORTS_VIEW,P.AUDIT_VIEW] },
] as const;
